simple calendar template
dsplay/template-simple-calendar pull request #1
Opened 2022-11-15 12:26 UTC by Kaue-G

2022-11-17 13:29 UTC, pcmnac requested changes
coloquei comentarios em arquivos especificos.

fora os comentarios, favor remover a pasta dist e remover os arquivos de fontes (e outros) que nao estejam sendo utilizados no projeto

2022-11-17 13:29 UTC, pcmnac commented on README.md
> +# Simple calendar - Template
adicionar a logo do DSPLAY e mudar o título para

DSPLAY - Simple Calendar

2022-11-17 13:29 UTC, pcmnac commented on public/dsplay-data.js
> +    result: { "validity": "2018-08-13T18:22:55.238Z", "showOutdated": true, "data": {} },
remover para nao confundir

2022-11-17 13:29 UTC, pcmnac commented on public/dsplay-data.js
> +    customMediaParam: "value",
remover para nao confundir

2022-11-17 13:29 UTC, pcmnac commented on public/dsplay-data.js
> +    template_var: "My Template Var",
remover todos aqui para nao confundir ja que este template nao tem nenhum parametro

2022-11-17 13:29 UTC, pcmnac commented on public/manifest.json
> +  "short_name": "React App",
colocar valores corretos

2022-11-17 13:29 UTC, pcmnac commented on package.json
> +  "name": "dsplay-template-react-boilerplate",
atualizar nome e versao

2022-11-17 13:29 UTC, pcmnac commented on src/Router.jsx
> +import React from 'react';
nao ha necessidade de um router para esse template

2022-11-17 13:29 UTC, pcmnac commented on src/contexts/calendarContext.jsx
> +import React, {
substituir esse componente pelo Loader que o sdk disponibiliza, para fazer pre carregamento de fontes, imagens ou dados que sejam utilizados pelo template. ver o exemplo to boilerplate-react

2022-11-17 13:29 UTC, pcmnac commented on src/fonts.sass
> +@font-face
remover fontes que nao estejam sendo usadas no template

2022-11-18 14:52 UTC, Kaue-G commented
Comentarios resolvidos e arquivos sem uso removidos.

2022-11-19 17:00 UTC, pcmnac approved these changes
coloquei alguns comentarios para serem ajustados num proximo pr, mas irei aprovar esse.

bom trabalho

2022-11-19 17:00 UTC, pcmnac commented on src/pages/Home/index.jsx
> +  useEffect(() => {
existe um hook useInterval() no sdk para esse tipo de situacao.

2022-11-19 17:00 UTC, pcmnac commented on src/pages/Home/index.jsx
> +function Home() {
mudar o nome desse componente para Main e colocalo na pasta de componentes para ficar no padrao do boilerplate

2022-11-19 17:01 UTC, merged